### ISSUE TITLE
C# version of this sample

### ISSUE THREAD

**Issue by MuleaneEve** [MicrosoftEdge/WebView2Browser#1]
Would you please consider writing a C# version of this sample?

It would make it much easier for us C# developers to dive into this new feature.

**Comment by yannduran** [comment]
Sorry, but this sample is of no use to me at all, seeing as I use C# for development.

**Comment by liminzhu** [comment]
Right now we only have the Win32 API preview but we are looking into building a WPF/WinForms control for WebView2 as well. We're focusing on getting win32 right first as the .NET control would be based on that anyways, but in time we'd want to include some tutorial/sample code for .NET for sure.

**Comment by MuleaneEve** [comment]
That's great to hear.
Thank you.

**Comment by ArgusMagnus** [comment]
Is there a time frame for the .NET release?

**Comment by giacomo33** [comment]
Any guidance on the .NET release preview?

**Comment by MuleaneEve** [comment]
I just found a C# port of this sample:
https://github.com/michael-russin/webview2-dotnetbrowser

This developer also created an [interop library](https://github.com/michael-russin/webview2-interop) and [controls for WinForms & WPF](https://github.com/michael-russin/webview2-control).
Awesome work!

**Comment by liminzhu** [comment]
We don't have an C# equivalent for this sample, but we do have a few .NET samples on our [samples repo](https://github.com/MicrosoftEdge/WebView2Samples).

**Comment by yannduran** [comment]
When is _WebView2_ going to no longer be dependent on the **_canary_** build of Edge (Chromium)?

I already have **Version 83.0.478.45 (Official build) (64-bit)** installed, and I don't want to have to install the canary version just to try _WebView2_ out in WPF.

**Comment by peiche-jessica** [comment]
@yannduran WebView2 for both Win32 C/C++ and .NET has reached GA.

More info about WebView2 runtime requirement can be found in our documentation:
https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning#matching-webview2-runtime-versions

If this is still an issue please let us know in [WebView2Feedback](https://github.com/MicrosoftEdge/WebView2Feedback). Thanks!
