### ISSUE TITLE
NuGet 2.0.9.538 doesn't contain the assembly

### ISSUE THREAD

**Issue by lucapivato** [MicrosoftEdge/WebView2Browser#18]
Updated the nuget and the WebView2 assemblies are gone. What am I missing?

**Comment by bgavrilMS** [comment]
I confirm, the package is empty

2.0.9.538
![image](https://user-images.githubusercontent.com/12273384/87045783-30027280-c1f0-11ea-88a5-406ff571acb3.png)

2.0.9.538-preview
![image](https://user-images.githubusercontent.com/12273384/87045832-40b2e880-c1f0-11ea-860c-f925d670fb55.png)

Please hide 2.0.9.538 from NuGet as it is broken.

**Comment by peiche-jessica** [comment]
This should have been fixed in later releases. If this is still an issue please let us know in [WebView2Feedback](https://github.com/MicrosoftEdge/WebView2Feedback). Thanks!
- https://docs.microsoft.com/microsoft-edge/webview2/releasenotes
