### ISSUE TITLE
Why is nobody talking HTA here?

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftEdge/WebView2Browser#26]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/533

https://github.com/MicrosoftEdge/WebView2Feedback/issues/533#issuecomment-709874573

This repo is even closer to HTA. I just bumped into it ... Built it and ... it does not want to open that ever-useful BING page ...

**Comment by victorhuangwq** [comment]
Closing it as it's addressed in the other repo
