### ISSUE TITLE
build release error

### ISSUE THREAD

**Issue by yangguang2015** [MicrosoftEdge/WebView2Browser#27]
build debug version is ok!
build release error!

**"CheckForDuplicateEntries": no "Microsoft::WRL::Details" member**
-----------------------------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(477,5): warning MSB8004: Output 目录未以斜杠结尾。  此生成实例将添加斜杠，因为必须有这个斜杠才能正确计算 Output 目录。
1>BrowserWindow.cpp
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1427,18): error C2039: "CheckForDuplicateEntries": 不是 "Microsoft::WRL::Details" 的成员
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1393): message : 参见“Microsoft::WRL::Details”的声明
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1540): message : 查看对正在编译的 类 模板 实例化“Microsoft::WRL::Module<Microsoft::WRL::InProc,ModuleT>”的引用
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1433,18): error C2039: "CheckForDuplicateEntries": 不是 "Microsoft::WRL::Details" 的成员
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1393): message : 参见“Microsoft::WRL::Details”的声明
1>Tab.cpp
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1427,18): error C2039: "CheckForDuplicateEntries": 不是 "Microsoft::WRL::Details" 的成员
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1393): message : 参见“Microsoft::WRL::Details”的声明
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1540): message : 查看对正在编译的 类 模板 实例化“Microsoft::WRL::Module<Microsoft::WRL::InProc,ModuleT>”的引用
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1433,18): error C2039: "CheckForDuplicateEntries": 不是 "Microsoft::WRL::Details" 的成员
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1393): message : 参见“Microsoft::WRL::Details”的声明
1>WebViewBrowserApp.cpp
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1427,18): error C2039: "CheckForDuplicateEntries": 不是 "Microsoft::WRL::Details" 的成员
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1393): message : 参见“Microsoft::WRL::Details”的声明
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1540): message : 查看对正在编译的 类 模板 实例化“Microsoft::WRL::Module<Microsoft::WRL::InProc,ModuleT>”的引用
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1433,18): error C2039: "CheckForDuplicateEntries": 不是 "Microsoft::WRL::Details" 的成员
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\wrl\module.h(1393): message : 参见“Microsoft::WRL::Details”的声明
1>已完成生成项目“WebViewBrowserApp.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by DH3650** [comment]
same problem while using Windows SDK 10.0.17763.0

upgrade ur Windows SDK to 10.0.18362.0, then build succeeded.

**Comment by windboy12138** [comment]
> same problem while using Windows SDK 10.0.17763.0
> 
> upgrade ur Windows SDK to 10.0.18362.0, then build succeeded.

Thanks a lot, it worked!
