### ISSUE TITLE
Project does not work

### ISSUE THREAD

**Issue by dhoelzl** [MicrosoftEdge/WebView2Browser#28]
Hello!

When I download the sample and open it with Visual Studio 2019, it does not run out of the box.

First, it complains about missing WebView2Loader.dll.

If I set the project to static linking (https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/static), it then complains about "The procedure entry point SetProcessDpiAwarenessContext" could not be located in the dynamic library ...".

What's wrong there?

I am running on Server 2012R2 with VS 2019 (16.0.1) and I have the latest WebView2Runtime (evergreen, standalone installer) installed.

Regards,
Dominik

**Comment by jimb15122** [comment]
Hi. As of 12/1/2020 having same problem.   
-Downloaded the project,.  
-Opened in vs2019.
- built debug x64 - no errors
- launched under debugger
- got file not found HR from creatcorewv2envwoptions
-used new get to uninstall then reinstall wv2 control v1.0.664.37
- same failure 

I then downloaded and installed the wv2 run time installer.

Now all is well.
Hope this helps
