### ISSUE TITLE
How to create new tab dynamically on ICoreWebView2NewWindowRequestedEventHandler event? 

### ISSUE THREAD

**Issue by Dave-Jalpan** [MicrosoftEdge/WebView2Browser#29]
How I can open new tab instead of new window? This is not bug but I am nav to C++ so not sure how to achieve this....

I have written following code to open new window in same tab but I want to open it in new tab instead. So, how to create new tab on ICoreWebView2NewWindowRequestedEvent? 

HRESULT BrowserWindow::HandleNewWindowRequested(size_t tabId, ICoreWebView2* webview, ICoreWebView2NewWindowRequestedEventArgs* args)
{
    wil::unique_cotaskmem_string uri;
    std::wstring str;
    if (SUCCEEDED(args->get_Uri(&uri)))
        str = uri.get();
    m_tabs.at(m_activeTabId)->m_contentWebView->Navigate(uri.get());
    ICoreWebView2Deferral *deferral;
    args->GetDeferral(&deferral); 
    return NULL;
}

**Comment by Dave-Jalpan** [comment]
@peiche-jessica @david-risney @mrsteamfist @champnic 
How to create new tab from C++ ICoreWebView2NewWindowRequestedEventHandler?

**Comment by Syul968** [comment]
Hi, @Dave-Jalpan 

You should be able to use [ICoreWebView2NewWindowRequestedEventArgs::put_NewWindow](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2newwindowrequestedeventargs?view=webview2-1.0.705.50#put_newwindow) to pass an `ICoreWebView2` to be used for the request. If you create a new tab (e.g., see `MG_CREATE_TAB` calling `Tab::CreateNewTab(...)`) you could then use it's `m_contentWebView` as target for the new window.

You would likely need to add a callback to `Tab::CreateNewTab(...)` so you can safely access the `m_contentWebView`; and update the UI for the new tab accordingly.

Hope this helps.
Thanks,
Luis

**Comment by Dave-Jalpan** [comment]
> Hi, @Dave-Jalpan
> 
> You should be able to use [ICoreWebView2NewWindowRequestedEventArgs::put_NewWindow](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2newwindowrequestedeventargs?view=webview2-1.0.705.50#put_newwindow) to pass an `ICoreWebView2` to be used for the request. If you create a new tab (e.g., see `MG_CREATE_TAB` calling `Tab::CreateNewTab(...)`) you could then use it's `m_contentWebView` as target for the new window.
> 
> You would likely need to add a callback to `Tab::CreateNewTab(...)` so you can safely access the `m_contentWebView`; and update the UI for the new tab accordingly.
> 
> Hope this helps.
> Thanks,
> Luis

@Syul968 Thank you for reply, between I had tried following but no success. I am more on to C# so not sure how to achieve what you said in C++ Win32 programming. Could  you please help to explain with example? 

What I tried so far is
```
HRESULT BrowserWindow::HandleNewWindowRequested(size_t tabId, ICoreWebView2* webview, ICoreWebView2NewWindowRequestedEventArgs* args)
{
wil::unique_cotaskmem_string uri;
std::wstring str;
if (SUCCEEDED(args->get_Uri(&uri)))
str = uri.get();
m_tabs.at(m_activeTabId)->m_contentWebView->Navigate(uri.get());
ICoreWebView2Deferral *deferral;
args->GetDeferral(&deferral);
return NULL;
}
```

```
HRESULT BrowserWindow::HandleNewWindowRequested(size_t tabId, ICoreWebView2* webview, ICoreWebView2NewWindowRequestedEventArgs* args)
{
    args->put_NewWindow(webview);
    return S_OK;
}
```

This is what i am trying to achieve.... 
![Try](https://user-images.githubusercontent.com/73806412/107447707-7e5b6380-6b7b-11eb-89ac-70001db11fa3.png)

**Comment by Dave-Jalpan** [comment]
@Syul968 Thank you for reply. I managed to open new window as a new tab, but now when I do not complete deferrer then caller tab get hang and if I complete deferrer then two windows (New window and new tab) appears. 

So may I know how to complete deferrer without new window?

```
    wil::unique_cotaskmem_string uri;
    std::wstring strUri;
    if (SUCCEEDED(args->get_Uri(&uri)))
        strUri = uri.get();
    std::wstring  endScript = L"');";
    std::wstring   URL = L"javascript:addTab('" + strUri  + endScript;
   
    m_controlsWebView->ExecuteScript( URL.c_str() ,Callback<ICoreWebView2ExecuteScriptCompletedHandler>(
    [](HRESULT errorCode, LPCWSTR resultObjectAsJson) -> HRESULT {
        return S_OK;
    }).Get());

    args->GetDeferral(&deferral); 
    return S_OK;
```

**Comment by peakpeak-github** [comment]
See https://github.com/MicrosoftEdge/WebView2Browser/issues/44 how I solved it.
You do not need any additional callbacks using this method as it's what the app is doing internally.
