### ISSUE TITLE
Gmail  tells me that the browser is not secure.

### ISSUE THREAD

**Issue by tobyg0** [MicrosoftEdge/WebView2Browser#34]
"This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can try again to sign in."

![image](https://user-images.githubusercontent.com/78401552/132264382-59ebda41-2d5c-4883-ad78-24f72403cf6d.png)

Is there anything I can add to fix this

**Comment by ekalchev** [comment]
Google doesn't allow logins from embedded browsers anymore. This has nothing to do with WebView2. It is the same with CEF. You should open desktop browser and let the user log from it.

**Comment by tobyg0** [comment]
> Google doesn't allow aouth requests from embedded browsers anymore. This has nothing to do with WebView2. It is the same with CEF. You should open OAuth page in desktop browser.
> 
> https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/

Thanks, I didn't know
