### ISSUE TITLE
Removing some things (Dev tools and Save as menu)

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/WebView2Browser#35]
As the title suggests how would I go about removing the dev tools and save as menu?

**Comment by Sir-Kam** [comment]
Yes it seems like you can, @tobyg0.
After seeing something in [BrowserWindow.cpp](https://github.com/MicrosoftEdge/WebView2Browser/blob/f527ec3525fd0507d222c5e6ae099fb10392e9aa/BrowserWindow.cpp#L253) about this I checked Microsoft's documentation for WebView2 and came across [ICoreWebView2Settings](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings) which is used to "enable, disable, or modify WebView features".

The members you're looking for are [put_AreDefaultContextMenusEnabled](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings#put_aredefaultcontextmenusenabled) and [put_AreDevToolsEnabled](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings#put_aredevtoolsenabled).


## Context menus:
```c++
/* Snippet from ICoreWebView2Settings documentation */

BOOL allowContextMenus;
CHECK_FAILURE(m_settings->get_AreDefaultContextMenusEnabled(&allowContextMenus));
if (allowContextMenus)
{
    CHECK_FAILURE(m_settings->put_AreDefaultContextMenusEnabled(FALSE));
    MessageBox(
        nullptr, L"Context menus will be disabled after the next navigation.",
        L"Settings change", MB_OK);
}
else
{
    CHECK_FAILURE(m_settings->put_AreDefaultContextMenusEnabled(TRUE));
    MessageBox(
        nullptr, L"Context menus will be enabled after the next navigation.",
        L"Settings change", MB_OK);
}
```

## Developer Tools:
```c++
/* Snippet from made up b/c there wasn't one in the documentation */

BOOL allowDevTools;
CHECK_FAILURE(m_settings->get_AreDevToolsEnabled(&allowDevTools));
if (allowDevTools)
{
    CHECK_FAILURE(m_settings->put_AreDevToolsEnabled(FALSE));
    MessageBox(
        nullptr, L"Dev tools will be disabled after the next navigation.",
        L"Settings change", MB_OK);
}
else
{
    CHECK_FAILURE(m_settings->put_AreDevToolsEnabled(TRUE));
    MessageBox(
        nullptr, L"Dev tools will be enabled after the next navigation.",
        L"Settings change", MB_OK);
}
```

(I know very little c++, so don't hurt me, but I just wanted to include what I found here in-case others stumble upon this- hope it helps)
