### ISSUE TITLE
Policy "NewTabPageManagedQuickLinks" error when more that 3 entries

### ISSUE THREAD

**Issue by mx4k** [MicrosoftEdge/WebView2Browser#37]
When you add a JSON with more than 3 links, the policy doesn't work anymore.
Edge shows an error with "value out of range".

Runtime: 96.0.1054.62
OS: Windows 10 19044.1415

Repro Steps
Set this as setting for the policy:

[ { "pinned": true, "title": "1", "url": "http://google.com" }, { "pinned": true, "title": "2", "url": "http://google.com" }, { "pinned": true, "title": "3", "url": "http://google.com" }, { "pinned": true, "title": "4", "url": "http://google.com" } ]

**Comment by alec-hs** [comment]
This is still and issue - can confirm Edge only accepts 3 links. 

Tested on Version 108.0.1462.54 (Official build) (64-bit)

**Comment by mx4k** [comment]
I don't know if the description was always like this but now it says that this is how it is expected to work.

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#newtabpagemanagedquicklinks

![grafik](https://user-images.githubusercontent.com/8719632/210581177-2f3a0a6a-d64a-4d06-9428-08e948d08299.png)

**Comment by champnic** [comment]
As noted, this is By Design.

This GitHub repo is also specifically for the WebView2 control Browser sample app. In the future for Microsoft Edge browser issues, please use the "Send Feedback" tool (alt+shift+i). Thanks!
