### ISSUE TITLE
Webview code samples

### ISSUE THREAD

**Issue by carondaniel1957** [MicrosoftEdge/WebView2Browser#38]
Good day I was wondering if it would be possible to have all code samples also written with VB language ?
I dont mind reading the C# or C++ codes samples but it does not serve me well.

Thanks for answering me

Daniel

**Comment by champnic** [comment]
Hey @carondaniel1957 - We have that request tracked here:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/265

But it's unlikely we'll get to it soon, unfortunately.
