### ISSUE TITLE
Requirements and problems

### ISSUE THREAD

**Issue by TheNPCFISH** [MicrosoftEdge/WebView2Browser#39]
When I started to run and debug the code I got message "you don't have g++". What is it and why do I get that message? Do I have to install something?

**Comment by champnic** [comment]
Hey @TheNPCFISH - "g++" is a compiler, but I'm not sure why you would have gotten that error for this project. What is your development environment? Are you using Visual Studio on Windows?

**Comment by TheNPCFISH** [comment]
> Hey @TheNPCFISH - "g++" is a compiler, but I'm not sure why you would have gotten that error for this project. What is your development environment? Are you using Visual Studio on Windows?

I use Visual Studio Code on Windows

**Comment by champnic** [comment]
Did you just launch the solution and try to build it?
What version of VS and Windows are you using?

**Comment by TheNPCFISH** [comment]
> Did you just launch the solution and try to build it?
> What version of VS and Windows are you using?

I don’t know. Because I am new to VS Code. 😄

**Comment by champnic** [comment]
Oh sorry, I missed the "Code" part. Can you try using Visual Studio? I'm not sure if VS Code can build the project out of the box. Our "Tutorials" have some good info on prerequisites for getting started with WebView2:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/get-started

**Comment by TheNPCFISH** [comment]
> Oh sorry, I missed the "Code" part. Can you try using Visual Studio? I'm not sure if VS Code can build the project out of the box. Our "Tutorials" have some good info on prerequisites for getting started with WebView2: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/get-started

Ok. Thank you!
