### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by TheNPCFISH** [MicrosoftEdge/WebView2Browser#41]
I saw that you support Visual Studio 2019 and 2017 but do you support 2022?

**Comment by TheNPCFISH** [comment]
> Yes, Visual Studio 2022 is supported. Where did you see this listed?

I saw it in README.md.

**Comment by champnic** [comment]
Oh gotcha. I'll open a bug to track getting that updated.

**Comment by TheNPCFISH** [comment]
> Oh gotcha. I'll open a bug to track getting that updated.

Ok. Thank you!
