### ISSUE TITLE
Errors and warnings

### ISSUE THREAD

**Issue by TheNPCFISH** [MicrosoftEdge/WebView2Browser#43]
When I am trying to build the solution. But there are errors:
![image](https://user-images.githubusercontent.com/93332534/164701888-5083407c-10fc-45a9-869b-957b5962dffd.png)
So can you fix this?

**Comment by PoweredByAndrox** [comment]
I fixed it with:
```vcpkg install cpprestsdk cpprestsdk:x64-windows```
From [Official cpprest Repo](https://github.com/microsoft/cpprestsdk)

**Comment by TheNPCFISH** [comment]
Thanks
